version: '3'
services:
  influxdb:
    image: influxdb:2.2.0
    ports: 
    - 8086:8086
    env_file:
      - influx.env
  mosquitto:
    image: eclipse-mosquitto:2.0.14
    ports:
      - 1883:1883
    volumes:
      - C:/Users/user/Desktop/hackatonVinc/GatewayConf/mosquitto.conf:/mosquitto/config/mosquitto.conf
    